### ISSUE TITLE
[bug]docker compose部署后浏览器访问失败-Content-Security-Policy

### ISSUE THREAD

**Issue by scylamb** [CaoMeiYouRen/rss-impact-server#333]
**Describe the bug/描述 bug**
docker compose部署后浏览器访问失败

A clear and concise description of what the bug is.<br/>
对 bug 是什么的清晰简洁的描述。

wget https://github.com/CaoMeiYouRen/rss-impact-server/blob/master/docker-compose.yml
docker compose up -d 启动 
部署后edge/firefox浏览器访问失败，域名/IP 访问都失败

```
Content-Security-Policy：由于违反了下列指令：“script-src 'self'”，此页面的内联脚本（script-src-elem）无法执行 single-file-extension-frames.js:1:295
Content-Security-Policy 警告 3
Content-Security-Policy：升级不安全的请求“http://10.10.200.201:3000/assets/index-DGYntj89.js”至使用“https”
Content-Security-Policy：升级不安全的请求“http://10.10.200.201:3000/assets/index-B_rwI6C7.css”至使用“https”
Content-Security-Policy：升级不安全的请求“http://10.10.200.201:3000/favicon.ico”至使用“https” 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://10.10.200.201:3000/assets/index-DGYntj89.js. (Reason: CORS request did not succeed). Status code: (null).
Module source URI is not allowed in this document: “http://10.10.200.201:3000/assets/index-DGYntj89.js”.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://10.10.200.201:3000/assets/index-B_rwI6C7.css. (Reason: CORS request did not succeed). Status code: (null).
```

**To Reproduce/再现**

Steps to reproduce the behavior:<br/>
再现行为的步骤：

**Expected behavior/预期行为**

A clear and concise description of what you expected to happen.<br/>
对你期望发生的事情的清晰简洁的描述。

**Screenshots/屏幕截图**
![image](https://github.com/user-attachments/assets/2e1b4fb5-8041-4384-b50b-30ecb468b35f)

![image](https://github.com/user-attachments/assets/5777cc89-763c-4e3e-93a4-1792549eb766)

If applicable, add screenshots to help explain your problem.<br/>
如果适用，请添加屏幕截图以帮助解释您的问题。

**Desktop (please complete the following information):/系统信息（请填写以下信息）：**

 - OS: Windows
 - Version 11

**Additional context/附加上下文**

Add any other context about the problem here.<br/>
在此处添加有关该问题的任何其他上下文。

**Comment by CaoMeiYouRen** [comment]
跨域了，是浏览器的问题，后端响应正常的。

具体请参考：https://rss-docs.cmyr.dev/docs/deploy#%E2%9A%99-%E9%85%8D%E7%BD%AE

```
# 启用跨域。如果前端和后端部署在不同域名下，需要跨域时，配置该项。
# ENABLE_ORIGIN_LIST=https://example1.com,https://example2.com
ENABLE_ORIGIN_LIST=''
```

**Comment by scylamb** [comment]
> 跨域了，是浏览器的问题，后端响应正常的。
> 
> 具体请参考：https://rss-docs.cmyr.dev/docs/deploy#%E2%9A%99-%E9%85%8D%E7%BD%AE
> 
> ```
> # 启用跨域。如果前端和后端部署在不同域名下，需要跨域时，配置该项。
> # ENABLE_ORIGIN_LIST=https://example1.com,https://example2.com
> ENABLE_ORIGIN_LIST=''
> ```

感谢答疑，但我尝试了半小时，测试都失败
```
ENABLE_ORIGIN_LIST='http://10.10.200.201:3000'
ENABLE_ORIGIN_LIST='http://10.10.200.201'
ENABLE_ORIGIN_LIST='http://www.domain.lamb,http://10.10.200.201'
ENABLE_ORIGIN_LIST='http://www.domain.lamb:3000,http://10.10.200.201:3000'
ENABLE_ORIGIN_LIST='*'
```

env 编辑方式是 docker compose 挂载进入容器中  
- ./.env:/app/.env
docker compose down && docker compose up -d

能否设置docker compose 默认情况下是允许任何来源跨域？

**Comment by CaoMeiYouRen** [comment]
> > 跨域了，是浏览器的问题，后端响应正常的。
> > 具体请参考：https://rss-docs.cmyr.dev/docs/deploy#%E2%9A%99-%E9%85%8D%E7%BD%AE
> > ```
> > # 启用跨域。如果前端和后端部署在不同域名下，需要跨域时，配置该项。
> > # ENABLE_ORIGIN_LIST=https://example1.com,https://example2.com
> > ENABLE_ORIGIN_LIST=''
> > ```
> 
> 感谢答疑，但我尝试了半小时，测试都失败
> 
> ```
> ENABLE_ORIGIN_LIST='http://10.10.200.201:3000'
> ENABLE_ORIGIN_LIST='http://10.10.200.201'
> ENABLE_ORIGIN_LIST='http://www.domain.lamb,http://10.10.200.201'
> ENABLE_ORIGIN_LIST='http://www.domain.lamb:3000,http://10.10.200.201:3000'
> ENABLE_ORIGIN_LIST='*'
> ```
> 
> env 编辑方式是 docker compose 挂载进入容器中
> 
> * ./.env:/app/.env
>   docker compose down && docker compose up -d
> 
> 能否设置docker compose 默认情况下是允许任何来源跨域？

使用`docker compose`部署时，请在 `docker-compose.yml`文件中的`environment`字段设置环境变量。

**Comment by scylamb** [comment]
> > > 跨域了，是浏览器的问题，后端响应正常的。
> > > 具体请参考：https://rss-docs.cmyr.dev/docs/deploy#%E2%9A%99-%E9%85%8D%E7%BD%AE
> > > ```
> > > # 启用跨域。如果前端和后端部署在不同域名下，需要跨域时，配置该项。
> > > # ENABLE_ORIGIN_LIST=https://example1.com,https://example2.com
> > > ENABLE_ORIGIN_LIST=''
> > > ```
> > 
> > 
> > 感谢答疑，但我尝试了半小时，测试都失败
> > ```
> > ENABLE_ORIGIN_LIST='http://10.10.200.201:3000'
> > ENABLE_ORIGIN_LIST='http://10.10.200.201'
> > ENABLE_ORIGIN_LIST='http://www.domain.lamb,http://10.10.200.201'
> > ENABLE_ORIGIN_LIST='http://www.domain.lamb:3000,http://10.10.200.201:3000'
> > ENABLE_ORIGIN_LIST='*'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > env 编辑方式是 docker compose 挂载进入容器中
> > 
> > * ./.env:/app/.env
> >   docker compose down && docker compose up -d
> > 
> > 能否设置docker compose 默认情况下是允许任何来源跨域？
> 
> 使用`docker compose`部署时，请在 `docker-compose.yml`文件中的`environment`字段设置环境变量。
能给个示例么？对于跨域这块我不太熟悉，我还是失败了，我想在http://10.10.200.201:3000上访问
```yml
version: "3"

services:
  server:
    # build: .
    container_name: 'rss-impact-server'
    image: ${DOCKER_IMAGE:-caomeiyouren/rss-impact-server}
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      TIMEOUT: 60000
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-123456123456}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      SESSION_SECRET: ${SESSION_SECRET:-RSS_IMPACT123456}
      RESOURCE_DOWNLOAD_PATH: './data/download'
      ENABLE_ORIGIN_LIST: "http://10.10.200.201:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
```
